general:
    #Number of questions for each quiz session
    questions-per-quiz: 5

    #Application language (ru, en)
    application-language: ru

#The paths to the question files
question-files:
    ru: /questions-db_ru.csv
    en: /questions-db_en.csv